name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i

      # Собираем приложение
      - name: Build Appliction
        run: npm run build

      # Собираем приложение
      - name: Generate static files
        run: npm run static-generate

      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: _static
          target: ~/public_html
          strip_components: 1
